# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class AVAInput(p.MessageType):

    def __init__(
        self,
        txid: bytes = None,
        index: int = None,
        asset: bytes = None,
        fxid: int = None,
        amount: int = None,
    ) -> None:
        self.txid = txid
        self.index = index
        self.asset = asset
        self.fxid = fxid
        self.amount = amount

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('txid', p.BytesType, 0),  # required
            2: ('index', p.UVarintType, 0),  # required
            3: ('asset', p.BytesType, 0),  # required
            4: ('fxid', p.UVarintType, 0),  # required
            5: ('amount', p.UVarintType, 0),  # required
        }
