# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class AVASignedTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 904

    def __init__(
        self,
        tx: bytes = None,
    ) -> None:
        self.tx = tx

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('tx', p.BytesType, 0),  # required
        }
